name: continuous-integration
on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v5
      with:
        path: main
        submodules: true
    - name: Update
      run: sudo apt-get update
    - name: Install Dependencies
      run: |
        sudo add-apt-repository universe
        sudo apt-get install --assume-yes python3-pip libfuse2t64
    - name: Checkout makelove
      uses: actions/checkout@v5
      with:
        repository: kongeor/makelove
        path: makelove
    - name: Install makelove
      run:
        pip3 install ./makelove
    - name: Build
      run: cd main/engine && python3 -m makelove --config ../makelove.toml
    - name: Artifact
      uses: actions/upload-artifact@v5
      with:
        name: DUMMY
        path: main/builds
